version: '2.4'
services:
  redmine:
    image: jouve/redmine
    build: .
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine
    ports:
    - 3000:3000
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: redmine
      POSTGRES_USER: redmine
      POSTGRES_DB: redmine
    volumes:
    - type: volume
      source: dbdata
      target: /var/lib/postgresql/data
volumes:
  dbdata:
